### ISSUE TITLE
1.13 colors are missing

### ISSUE THREAD

**Issue by uncovery** [Minecraft-Technik-Wiki/BlockMap#4] opened 2018-11-09 06:22 UTC
Missing color for minecraft:stone_slab,type=bottom
 Missing color for minecraft:stone_brick_stairs,facing=south,half=bottom,shape=straight
 Missing color for minecraft:stone_brick_stairs,facing=north,half=bottom,shape=straight
 Missing color for minecraft:oak_stairs,facing=north,half=bottom,shape=straight

etc.

**Comment by piegamesde** [comment] 2018-11-09 08:59
Do you have a world that reproduces this? These block states are missing on purpose because normally, they should also have the `waterlogged`-property. So the full name of the blocks would be `minecraft:stone_brick_stairs,facing=south,half=bottom,shape=straight,waterlogged=false`, `minecraft:stone_brick_stairs,facing=south,half=bottom,shape=straight,waterlogged=true` etc. Due to performance reasons blocks with not all possible state properties are declared as missing color.

Normally, Minecraft worlds should never contain one of those blocks you listed above. But I recently found out that for some reason, "optimized" Minecraft world from previous versions do not have the `waterlogged` property (This may be intended behavior or a bug, but since it's not on my side please contact Mojang if you want this to change). The current workaround is to load the world and fly a bit through it. The chunks that were loaded in game should not have any missing blocks.

**Comment by uncovery** [comment] 2018-11-09 09:02
Yes, I have a world here like this.

**Comment by piegamesde** [comment] 2018-11-09 09:21
Maybe you could misuse the [Minecraft Land Generator](https://github.com/Morlok8k/MinecraftLandGenerator) to do this for you?

**Comment by piegamesde** [comment] 2018-11-09 21:41
I am going to close this, as this is a Minecraft bug and working around it in BlockMap is not worth all the costs, both performance- and development-wise.

**Closed by piegamesde** 2018-11-09 21:41 UTC
Labels: wontfix

**Comment by uncovery** [comment] 2018-11-09 22:57
Yeah I agree. Thanks!
