### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by uncovery** [Minecraft-Technik-Wiki/BlockMap#31] opened 2019-10-02 16:41 UTC
## Environment info

- **BlockMap version**: `BlockMap-cli-1.5.1.jar`
- **Java version**: openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment 19.3 (build 12.0.2+9)
OpenJDK 64-Bit Server VM 19.3 (build 12.0.2+9, mixed mode, sharing)
- **Operating system**: `CentOS 7, Linux 3.10.0-862.2.3.el7.x86_64` 

## Description
I get the following warnings:
> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor (file:/home/minecraft/server/blockmap/BlockMap-cli-1.5.1.jar) to constructor java.util.Optional()
> WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

## Steps to reproduce

1. java -jar BlockMap.jar -v render ./region --create-big-image --min-X=-2048 --max-X=2048 --min-Z=-2048 --max-Z=2048 -o ./png  --create-tile-html

**Comment by piegamesde** [comment] 2019-10-04 21:10
> Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor

BlockMap only uses GSON as dependency, I do not maintain that class. You should file the bug to them instead.

This may be a duplicate of https://github.com/google/gson/issues/1540

**Closed by piegamesde** 2019-10-04 21:10 UTC
